=== Yashuke03/Library-api/PS 12: Online Shop Inventory/inventory.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">

  <xsd:element name="inventory">
    <xsd:complexType>
      <xsd:sequence>

        <xsd:element name="product" maxOccurs="unbounded" minOccurs="1">
          <xsd:complexType>
            <xsd:sequence>

              <!-- Product ID -->
              <xsd:element name="productId" type="xsd:integer"/>

              <!-- Name -->
              <xsd:element name="name" type="xsd:string"/>

              <!-- Category restriction -->
              <xsd:element name="category">
                <xsd:simpleType>
                  <xsd:restriction base="xsd:string">
                    <xsd:enumeration value="Electronics"/>
                    <xsd:enumeration value="Clothing"/>
                    <xsd:enumeration value="Food"/>
                  </xsd:restriction>
                </xsd:simpleType>
              </xsd:element>

              <!-- Stock must be >= 0 -->
              <xsd:element name="stock">
                <xsd:simpleType>
                  <xsd:restriction base="xsd:integer">
                    <xsd:minInclusive value="0"/>
                  </xsd:restriction>
                </xsd:simpleType>
              </xsd:element>

              <!-- Price -->
              <xsd:element name="price" type="xsd:decimal"/>

            </xsd:sequence>
          </xsd:complexType>
        </xsd:element>

      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>

</xsd:schema>

=== Yashuke03/Library-api/PS 12: Online Shop Inventory/inventory.xml
<?xml version="1.0" encoding="UTF-8"?>

<inventory xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:noNamespaceSchemaLocation="inventory.xsd">

  <product>
    <productId>1</productId>
    <name>Laptop</name>
    <category>Electronics</category>
    <stock>10</stock>
    <price>55000.50</price>
  </product>

  <product>
    <productId>2</productId>
    <name>T-Shirt</name>
    <category>Clothing</category>
    <stock>25</stock>
    <price>799.99</price>
  </product>

  <product>
    <productId>3</productId>
    <name>Chocolate</name>
    <category>Food</category>
    <stock>50</stock>
    <price>150.00</price>
  </product>

  <product>
    <productId>4</productId>
    <name>Headphones</name>
    <category>Electronics</category>
    <stock>15</stock>
    <price>1999.99</price>
  </product>

  <product>
    <productId>5</productId>
    <name>Jeans</name>
    <category>Clothing</category>
    <stock>20</stock>
    <price>1499.50</price>
  </product>

</inventory>
